### PR TITLE
enable click event handling of items in menu

### PR DESCRIPTION
**Pull request by tmclane**
Adding click event processing to the components listed in the menu makes this example a bit more complete.

### CODE REVIEW

**Comment by justindujardin** [comment]
@tmclane thanks for the PR.  

We actually intentionally don't use (click) event handling because we don't want to navigate to the new page until the ink-drop animation has fully played through.  This makes sure the animation doesn't look "chunky" when switching between demos.

**Comment by tmclane** [comment]
Ah ok.  How do you use the items in the sidenav to navigate?
Is there another way?

**Comment by justindujardin** [comment]
The `md-ink` directive on the sidenav item fires an `inked` event when its ink animation is done, and we call a method `navigate` on the menu view:
```html
<md-list-item md-ink (inked)="navigate(['Component', {id: value.id}])"
              [class.md-active]="navigation?.currentTitle==value.name"
              *ngFor="#value of components">
{{value.name}}
</md-list-item>
```

The view method invokes the router manually:

```typescript
  navigate(to:any) {
    this.router.navigate(to);
  }
```

**Comment by tmclane** [comment]
Apparently it wasn't working for me on Chrome or Safari on a Mac.  I didn't
try Firefox.  Maybe it works now?

**Comment by tmclane** [comment]
Yes it is working now.  Please don't worry about this anymore.

**Pull request closed without merging**
