### PR TITLE
Refactor/shadows

### PR DESCRIPTION
**Pull request by axal90**
I reworked the way shadows where handled.
Using elevation from Material2 instead of the whiteframe implementation.
Added utility examples

Breaking change:

- `.md-whiteframe-z*` and `.md-whiteframe-*dp` are now replaced by `.md-elevation-z*`
- `$whiteframe-shadow-z1;` is deprecated use `@include md-elevation(1);` instead

@justindujardin could you help out with a propper commit message?

### CODE REVIEW

**Comment by justindujardin** [comment]
@axal90 I think we should start importing these directly from the material2 packages that we npm install.  In this case, I think the PR would be more appropriate to import the styles from the `core` package of material2, and update the examples to use those styles (removing whiteframe if appropriate).

I want to be respectful of the material2 team now that they're releasing, by using their code through the official packages (as peer dependencies) and removing any duplicate stuff in ng2-material's code base.

What do you think?

**Comment by zigzag95** [comment]
@justin why not create a branch of material2 and put in ng2 components?

**Comment by axal90** [comment]
@justindujardin I watched their talk from ng-conf and was thinking the same. Just didnt have time to redo it.
I'll have a updated PR tomorrow. :)

**Comment by axal90** [comment]
Was such an easy change so got it going tonight. 
This PR is dependent on angular 2 rc #207
also it adds angular-material/core as dependency wich can be used in #202 and #200 and for dialogs

**Comment by justindujardin** [comment]
@axal90 please apply this directly to the rc0-material2 branch. :)

**Pull request closed without merging**
