### PR TITLE
Upgrade to angular rc4

### LINKED ISSUE #248: Click event is being called twice on a selectable data-table when clicking checkbox
When i click on any part of the tr it works ok, but when checkbox is clicked, the code below is executed  two times:
<pre>
<b>component: <i>users-list.ts</i></b>
[...]
 change(data: ITableSelectionChange) {
    console.log(data);
    let names = [];
    this.materials.forEach((mat: any) => {
      if (data.values.indexOf(mat.id) !== -1) {
        names.push(mat.name);
      }
    });
    this.selection = names.join(', ');
    this.count = names.length;
  }
[...]
</pre>
Causing the following result in chrome:

but the expected behavior is:

So i suspect that maybe is a problem related with event propagation between checbox and tr, or i am making a mistake that im not seeing because it seems to work fine in documentation's site.

### LINKED ISSUE #268: Supporting RC2 or 3 of Angular 2?
Hi guys, is there any timeframe on supporting RC2 or 3 of Angular2. Currently, if I try to install on npm I get errors as I am not using RC1.

### PR DESCRIPTION
**Pull request by Gregcop1**
Upgrade:
- angular : 2.0.0-rc.4
- @angular2-material: 2.0.0-alpha.6-2
- @angular/router: 3.0.0-alpha.8

A big thanks to @Tallyb and @vincentpalita for their help on this one
@justindujardin @ollwenjones Can you review this one please ?

Fix #268
Fix #248

### CODE REVIEW

**Comment by Tallyb** [comment]
I think you can upgrade the router to 3.0.0-beta.2 with no impact.

**Comment by justindujardin** [comment]
Is this dependency mismatch (forms ^0.1.0 -> ^0.2.0) significant?

`npm WARN @angular2-material/checkbox@2.0.0-alpha.6-2 requires a peer of @angular/forms@^0.1.0 but none was installed.`

**Comment by Tallyb** [comment]
should probably upgrade to 0.2.0. seems not to have any breaking changes.

**Comment by justindujardin** [comment]
There is a problem with the code highlight component in the examples site.

If you load the site on the data-table component, then navigate to the dialog component page, the examples are not highlighted:
screen shot 2016-07-16 at 9 03 10 am

If you refresh the page from there they are properly highlighted: 
screen shot 2016-07-16 at 9 03 24 am

**Comment by vincentpalita** [comment]
We need to fix the MdMessages directive aswell. Just sent a comment on Gitter about that, I am almost done upgrading it.

**Comment by Gregcop1** [comment]
@justindujardin Official comment about the peerdependency is this : https://github.com/angular/material2/issues/849

**Comment by justindujardin** [comment]
I fixed the issue with highlight not working after changing routes.  

This PR looks straightforward and ready to go as soon as the issues you have identified are resolved and the build is passing.  

Please feel free to merge when that happens. 👍

**Comment by chiefmc** [comment]
Hey everyone!

When we're ought to expect these changes to be released to npm?

**Comment by justindujardin** [comment]
@Tallyb @vincentpalita I'm afraid that when I merged this commit, the squashing of the commits into one seems to have lost your commit contributions. As a result your names were not added to the package.json contributor list when I did the npm release.  

I'd like to make sure you both end up in contributor list. Would you please open a PR with some modifications to something minor like the README.md file, so that I can add your contribution and get you in the list?

Sorry for the inconvenience, and thanks for your contributions!

**Pull request merged**
