### PR TITLE
Feature | Chip component

### PR DESCRIPTION
**Pull request by axal90**
A initial commit to spark a conversation about the implementation.

Looking for feedback especially on how i use the service for storing the array.

At the moment there is no output.

Still to do:
- Create a readonly state with input value instead of text input
- Add output in a usable way. (event or observable?)
- Allow for user defined templates for chips.
- Allow for user defined input field (for autocomplete, placeholder...)
- Backspace should delete last chip.
- Event for selected chip.

### CODE REVIEW

**Comment by justindujardin** [comment]
@axal90 cool start, thanks for putting it forward!

I played around with what you did a bit over the last day or so. I pushed a branch that looks good across a few browsers and is consistent with the latest material spec page.

 - added `deletable` bindings (it's the word used in the spec) to control whether or not the x is visible.
 - support deleting the last chip by hitting backspace with an empty input. 
 - added an MdChipsInput directive to encapsulate the typing input behaviors.
 - remove some unneeded wrapper elements and simplify templates.
 - break component styles out into files that correspond to their particular part of the chips component.

It feels pretty nice, but the thing that's not clear to me yet is how to bind a data source into it easily.  I think the data service is tripping me up a bit. I will look at it again when I have some time--probably next weekend.

https://github.com/justindujardin/ng2-material/tree/chips

I think there are a few things we'll need to do before we can merge any form of this component:

 - Add tests about its behavior and coverage to an acceptable level
 - Add examples of how to bind to it with observable collections and regular arrays

**Comment by axal90** [comment]
@justindujardin Nice work! 

I shamelessly copied the structure and styles from angular material just to get going.
Thanks for cleaning it up.

I took your code since it looks way better!
Added some things to it.

- Placeholder for the input
- Readonly mode (no input field)
- Unique, if set to true only adds a chip if one with the same label does not already exist.


I'm new to observables and they are a bit mindbending :p
But I will have a look at binding data into it.

It would be nice to have an onChange event.
Is there any way we could bubble an event from the service? 
Or can we somehow detect when the data changes?

I'm ashamed to admit that testing is really not my forte, but I will look into it.

**Comment by justindujardin** [comment]
@axal90 I checked out what you did and added another step towards something workable.  

To make things easier I've added you as a collaborator to this repo.  Please checkout the `chips` branch and push your commits there so we can work in the same place.

Don't worry too much about the tests, I can help you with them over the weekend.

**Comment by justindujardin** [comment]
@axal90 let's continue this PR in #208 

I'll close this one because it's connected to your fork of the project.

**Pull request closed without merging**
