### PR TITLE
feat/rc3: migration to rc3

### PR DESCRIPTION
**Pull request by prashanthcvvp**

### CODE REVIEW

**Comment by Gregcop1** [comment]
Hi. Thanks for your contribution but I think you forgot to update all tests

**Comment by ollwenjones** [comment]
Any reason not to go all the way to 4? (There were a lot more breaking changes to tests going from 3 > 4 than 2 >3

**Comment by Gregcop1** [comment]
angular/material2 is still on RC3 so we have to stay on RC3 :/

**Comment by YeomansIII** [comment]
Hi.  I think you should also be updating angular/material2 to alpha.6, correct?  Also, it seems they are rather close at updating to rc.4. https://github.com/angular/material2/pull/843

**Comment by mebyz** [comment]
+1 for going rc4 : https://github.com/angular/material2 has been updated to handle rc4

**Comment by Gregcop1** [comment]
Ohhhh nice. So let's work on RC4. Thanks for the info @mebyz

**Pull request closed without merging**
