### PR TITLE
Fix inputs provisionned after init

### PR DESCRIPTION
**Pull request by pallmallshow**
Hi,

Referred to Issue #39 .

I changed the condition to check if value is empty or not.

### CODE REVIEW

**Comment by ollwenjones** [comment]
These tests are failing because the browsers aren't starting...

**Comment by justindujardin** [comment]
Please rebase on the latest master to fix the travis build issue for PRs.

**Comment by justindujardin** [comment]
@pallmallshow I'd like to have a test to cover how this was failing before and see it pass with your changes. Is this something you can do? There is an input test already, so adding another should be a breeze. See: https://github.com/justindujardin/ng2-material/blob/master/test/components/input/input_spec.ts#L73

**Comment by sylvaindumont** [comment]
The fix work well with data coming from http, but 'undefined' is written in all blanks input.

**Pull request closed without merging**
