### PR TITLE
Added support for building single js file using webpack

### PR DESCRIPTION
**Pull request by dotansimha**
- Added webpack build process which adds to the `out` directory a single js file.
- The file is consumable by CommonJS.
- Two new out files: 
`all-webpack.js`- contains all JS files, fonts, fonts css and CSS files.
`all-styles.js`- contains all fonts, fonts css and CSS files.
- Updated the Grunt build process to run this when building.

Those files are requires for platforms that supports NPM modules but does not support the ability to import assets from node_modules, such as Meteor 1.3-beta7 (**at the moment there is no support, might change**)

### CODE REVIEW

**Comment by justindujardin** [comment]
Thanks for the PR!  

Please tell me a bit more about the need for having a WebPack build in addition to the System.JS outputs that are already provided. Is it just for CommonJS modules?  Could System Builder be used to accomplish the same thing?

Also: If you rebase the PR on the latest master, it will build with Travis properly.

**Comment by dotansimha** [comment]
hi @justindujardin ,
Meteor 1.3 provides the ability to use modules from NPM (node_modules), but it still does not have the ability to import assets files (such as fonts, css, images, etc..). The new bundle I added provides a single JS file that can be imported, and the assets are bundled inside the JS file instead of an external file.

**Comment by ollwenjones** [comment]
Also the webpack _really_ prefers implementers pull in src/raw files, rather than pre-built files, so it can de-duplicate dependencies, manage the code-splitting, etc.

+1

**Comment by justindujardin** [comment]
@dotansimha I pulled this in to master with a few changes.

- removed the ./webpack path and put the webpack files in ng2-material as typescript.
- changed the final output files to: `all.webpack.js` and `all.webpack.styles.js`

Thanks for the submission.

**Pull request closed without merging**
