### PR TITLE
Added support for InkBar when using Tab component. Plus tab bodies now slide in from the left/right

### PR DESCRIPTION
**Pull request by steve-farr**
Active tab is highlighted by an ink bar. It moves as a new tab is selected.

Changes have been to add new InkBar component class, which is passed into MdTabs. When a new tab is selected, the movement of the InkBar is done via changes to the style of the InkBar implemented in Ink.ts

(Note the build is failing because Angular2 has been updated to Beta 16. Beta 16 has currently broken other parts of ng2-material, unrelated to the changes I have made. I have tested it against Beta 15)

### CODE REVIEW

**Comment by steve-farr** [comment]
Second set of changes adds support for sliding in of the tab content. To do this, I've had to change the existing way tabs are defined (it's a breaking change but simple to correct). They were defined using templates like this:
    <template md-tab...>
and now they need to be defined as follows, which is more in line with how material design defines tabs
    <md-tab...>
This is so MdTab can be component rather than just a directive. It needs to add <md-tab-content> around the user defined tab content.
This tag is needed to enable the sliding effect that's defined in the CSS in md-tab-content>md-left/right
It also helps simplify the setting of the CSS styles as they can be enabled based on a position property rather than just a boolean active property. Position stores whether the tab is left or right of the active tab or if it's the actual active property.

**Comment by justindujardin** [comment]
Thanks for the contribution! Please rebase your branch and remove the commit that bumps the version--I run that task when deploying a build to NPM, it's not appropriate to run it as part of feature development.

**Comment by steve-farr** [comment]
Sorry about that extra commit - it accidentally got included.

It's now removed and so the two included commits are for the two intended changes.

**Comment by justindujardin** [comment]
Thanks for the contribution, sorry it didn't work out to get it merged.  We deprecated the ng2-material tabs component in favor of the [material2/tabs](https://github.com/angular/material2/tree/master/src/components/tabs) package.  Closing this because of that.

**Pull request closed without merging**
